apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone
    role: rolling
    env: production
spec:
  type: LoadBalancer
  selector:
    app: capstone
    role: rolling
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
