apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-${ROLE}
  labels:
    app: nginx
    role: ${ROLE}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        # example:
        # - name: api
        #   image: minorpath/capstone-nginx:${ROLE}
        #   ports:
        #   - containerPort: 80
        - name: nginx
          image: nginx:1.18.0-alpine
          ports:
            - containerPort: 80
