apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstone
      role: green
  template:
    metadata:
      labels:
        app: capstone
        role: green
    spec:
      containers:
        - name: nginx
          image: minorpatch/capstone-nginx:green
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
        - name: flask
          image: minorpatch/capstone-flask:green
          imagePullPolicy: "Always"
          env:
            - name: APP_NAME
              value: "GREEN APP"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
